### ISSUE TITLE
error under linux

### ISSUE THREAD

**Issue by eventcatcher** [lamnhan066/language_code#4]
Hi, 

I've found a problem under Linux (Ubuntu 22.04 ARM64) if i trying to start the app:

Launching lib/main.dart on Linux in debug mode...
✓ Built build/linux/arm64/debug/bundle/roonmatrix
libGL error: pci id for fd 11: 1ab8:0010, driver (null)
pci id for fd 12: 1ab8:0010, driver (null)

(roonmatrix:7258): Gdk-CRITICAL **: 09:28:45.886: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed

(roonmatrix:7258): Gdk-CRITICAL **: 09:28:45.886: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed

(roonmatrix:7258): Gdk-CRITICAL **: 09:28:46.043: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
Connecting to VM Service at ws://127.0.0.1:35803/QW5pce3kqUM=/ws
Connected to the VM Service.

(roonmatrix:7258): Gdk-CRITICAL **: 09:28:48.113: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
(roonmatrix:7258): Gdk-CRITICAL **: 09:28:48.113: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
(roonmatrix:7258): Gdk-CRITICAL **: 09:28:59.474: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
(roonmatrix:7258): Gdk-CRITICAL **: 09:29:04.457: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
(roonmatrix:7258): Gdk-CRITICAL **: 09:29:04.457: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
(roonmatrix:7258): Gdk-CRITICAL **: 09:29:04.543: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
(roonmatrix:7258): Gdk-CRITICAL **: 09:29:04.543: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
(roonmatrix:7258): Gdk-CRITICAL **: 09:29:05.844: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
(roonmatrix:7258): Gdk-CRITICAL **: 09:29:06.234: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
(roonmatrix:7258): Gdk-CRITICAL **: 09:29:06.234: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
(roonmatrix:7258): Gdk-CRITICAL **: 09:29:23.617: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
(roonmatrix:7258): Gdk-CRITICAL **: 09:29:23.617: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
(roonmatrix:7258): Gdk-CRITICAL **: 09:29:23.743: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed
(roonmatrix:7258): Gdk-CRITICAL **: 09:29:23.776: gdk_device_get_source: assertion 'GDK_IS_DEVICE (device)' failed

Without language_code package, it works successfully.

**Comment by lamnhan066** [comment]
Hi @eventcatcher 

As I have checked, those logs are fired by the GTK library used by the Flutter framework. Did you get the result language code by using this?

> ```
> Locale locale = LanguageCode.code.locale;
> String languageCode = locale.languageCode;
> ```

**Comment by eventcatcher** [comment]
Ah, it looks like the Gdk-CRITICAL thing is not he problem here.
If i disable both lines of LanguageCode code, the app is running fine.
If I enable the first line ( Locale locale = LanguageCode.code.locale ), the app opens a black window without content.

**Comment by eventcatcher** [comment]
A exception is occurred here:

`in language_codes.dart

/// Get [LanguageCodes] from string [code]. If no matching element is found,
  /// returns the result of [orElse]. If [orElse] is omitted, it defaults to
  /// throwing a [StateError]
  static LanguageCodes fromCode(
    String code, {
    LanguageCodes Function()? orElse,
  }) {
>>  return LanguageCodes.values
        .singleWhere((element) => element.code == code, orElse: orElse);
  }
`

`.pub-cache/hosted/pub.dev/bloc-8.1.4/lib/src/bloc.dart:
       final emitter = _Emitter(onEmit);
        final controller = StreamController<E>.broadcast(
          sync: true,
          onCancel: emitter.cancel,
        );

        Future<void> handleEvent() async {
          void onDone() {
            emitter.complete();
            _emitters.remove(emitter);
            if (!controller.isClosed) controller.close();
          }

          try {
            _emitters.add(emitter);
            await handler(event as E, emitter);
          } catch (error, stackTrace) {
            onError(error, stackTrace);
>>          rethrow;
          } finally {
            onDone();
          }
        }
`


<img width="1131" alt="screenshot 2024-09-20 um 07 22 58" src="https://github.com/user-attachments/assets/d6e15149-2913-4d0d-aeec-d2dfa61a6dc1">

**Comment by eventcatcher** [comment]
At runtime, LanguageCodes fromCode, code is 'c'. Is this right? I would have expected a code like 'en'.

**Comment by eventcatcher** [comment]
LanguageCode.rawLocale results in 'C'

**Comment by lamnhan066** [comment]
I just did a quick search. The locale `C` (or `POSIX`) stands for the standard C locale (which is the `en_US` by default), which is most likely available only on Linux devices  (Source: [stackoverflow](https://stackoverflow.com/questions/10831839/in-google-analytics-what-does-the-locale-c-stands-for) and [Apache](https://stdcxx.apache.org/doc/stdlibug/24-3.html)).

Because it's a special case (not in the locale list that I use), so I think I need to check it and return `en_US` to avoid this issue.

**Comment by eventcatcher** [comment]
Ah, strange thing, but very cool you've found a solution to fix!

**Comment by eventcatcher** [comment]
New build 0.5.4 is running fine now.
