### ISSUE TITLE
[PROPOSAL]: add PRS & SDH locales

### ISSUE THREAD

**Issue by msonntag13** [lamnhan066/language_code#6]
### Proposal:
As PRS (Dari) and SDH (Southern Kurdish) are not covered by the package yet I'd like to propose adding them.

These languages are not supported by Flutter per default (but can be added manually), but in regards of rising numbers of refugees speaking these languages in Europe I'd love to see them covered. 

I've already prepared the enum entries:
```
/// code: "prs", name: "Dari", nativeName: "دری"
prs("prs", "Dari", "دری"),
```

```
/// code: "sdh", name: "Southern Kurdish", nativeName: "کوردی خوارین"
sdh("sdh", "Southern Kurdish", "کوردی خوارین"),
```

Please let me know if you need anything else or if I can help somehow.

### Sources:
https://en.wikipedia.org/wiki/Dari
https://en.wikipedia.org/wiki/Southern_Kurdish

**Comment by lamnhan066** [comment]
Hi @msonntag13,

Should add the [Kurdish](https://en.m.wikipedia.org/wiki/Kurdish_language) first?

**Comment by msonntag13** [comment]
Hey @lamnhan066,

Kurdish itself is already supported as far as I can see in [language_codes.dart#L1259](https://github.com/lamnhan066/language_code/blob/16edf339048cc377987e6a9ea949b8bf930d3ba6/lib/src/language_codes.dart#L1259):
```
/// code: "ku", name: "Kurdish", nativeName: "Kurdî"
ku("ku", "Kurdish", "Kurdî"),
```

However it could make sense to support [Northern Kurdish/Kurmanji](https://en.m.wikipedia.org/wiki/Kurmanji), [Central Kurdish/Sorani](https://en.m.wikipedia.org/wiki/Sorani) and [Laki](https://en.m.wikipedia.org/wiki/Laki_language) dialects as well alongside [Southern Kurdish](https://en.wikipedia.org/wiki/Southern_Kurdish).

Do you want me to prepare the enum entries for these as well so we can add all of them together?

**Comment by lamnhan066** [comment]
> Kurdish itself is already supported as far as I can see in [language_codes.dart#L1259](https://github.com/lamnhan066/language_code/blob/16edf339048cc377987e6a9ea949b8bf930d3ba6/lib/src/language_codes.dart#L1259):

Ah, I see. But what do you think about `Kurdî` and `کوردی`? If we keep this value `Kurdî`, the `sdh("sdh", "Southern Kurdish", "کوردی خوارین")` will be looked inconsistent. I think the `کوردی` looks more like native than `Kurdî`.

> Do you want me to prepare the enum entries for these as well so we can add all of them together?

Yes, of course. Thank you!

**Comment by msonntag13** [comment]
Good point! I'd opt for `کوردی` as well there, `Kurdî` isn't even the correct alphabet to be considered "native" since it's just the romanized notation.

Then the doing would be the following:

**_UPDATE [language_codes.dart#L1259](https://github.com/lamnhan066/language_code/blob/16edf339048cc377987e6a9ea949b8bf930d3ba6/lib/src/language_codes.dart#L1259) TO_**
```
/// code: "ku", name: "Kurdish", nativeName: "Kurdî"
ku("ku", "Kurdish", "کوردی"),
```

**_ADD_**
```
/// code: "ckb", name: "Sorani", nativeName: "کوردیی ناوەندی"
ckb("ckb", "Sorani", "کوردیی ناوەندی"),
```
```
/// code: "kmr", name: "Kurmanji", nativeName: "کورمانجی"
kmr("kmr", "Kurmanji", "کورمانجی"),
```
```
/// code: "lki", name: "Laki", nativeName: "له‌کی"
lki("lki", "Laki", "له‌کی"),
```
```
/// code: "prs", name: "Dari", nativeName: "دری"
prs("prs", "Dari", "دری"),
```
```
/// code: "sdh", name: "Southern Kurdish", nativeName: "کوردی خوارین"
sdh("sdh", "Southern Kurdish", "کوردی خوارین"),
```

**Comment by lamnhan066** [comment]
Would you like to create a PR for those updates?

**Comment by msonntag13** [comment]
Sure thing, however I don't think I'm allowed to create branches

**Comment by lamnhan066** [comment]
To create branches, you need to `fork` the repo first. I don't think I have applied any special security features to this repository.

**Comment by lamnhan066** [comment]
I'll close this issue as the PR was merged. Thank you for your contribution!
